### ISSUE TITLE
"inet_tcp",{{badmatch,{error,duplicate_name}} start/console bug

### ISSUE THREAD

**Issue by RobertLowe** [basho/riak#122] opened 2012-03-06 03:04 UTC
Howdy,

This just went out on the mailing list, but it was suggest that I should post here as well.

http://markmail.org/message/pjqo5qbdtepbfhit
http://hastebin.com/wucipobiho - Someone else having the same issue

For some reason and I'm not completely sure of the root cause. My uneducated guess is something with epmd. It seems to be a general erlang issue. [ejabberd report](http://www.ejabberd.im/error/duplicate_name), [rabbitmq report](http://old.nabble.com/RabbitMQ-on-Mac-td28594651.html)

After `riak start` no crash is produced, but any command will see "Node is not up / not responding to pings."

However, if you run `riak console`, the crash snippet from above is produced.

If you kill -9 all riak processes, and then run `riak console`, then exit, then `riak start` the issue vanishes.

Is there a safe way we can handle this issue?

Thanks,
- Rob

**Comment by Vagabond** [comment] 2012-03-06 15:32
As the links you include say, this is caused by 2 nodes trying to use the same name (and the second one failing). empd -names will show you all the locally registered node names.

Is it possible you're inadvertantly trying to start riak twice?

**Comment by RobertLowe** [comment] 2012-03-13 00:07
@Vagabond 

Sorry for the wait, yup, that was the issue. 

I'll wrap it with some kind of lock.

Thanks a bunch!

**Comment by krestenkrab** [comment] 2012-05-18 09:13
It seems that _everyone_ starting out with Erlang has this issue at some point.  Why not provide a more descriptive error message somehow?

**Comment by PharkMillups** [comment] 2012-05-18 22:56
I'm not sure why, but it looks like I closed this issue. I don't recall doing it. Regardless, it was done in error. Reopening so that someone more capable than I can close it for the right reasons.

**Closed as completed** 2012-07-26 06:31 UTC
Labels: Kanban-Backlog
