### ISSUE TITLE
Typo in riak_client:stream_list_keys/4

### ISSUE THREAD

**Issue by brianshumate** [basho/riak#142] opened 2012-05-22 12:40 UTC
At line 543 in `riak_client`, the module name appears to be singular `build_filter` when perhaps it should be plural `build_filters`.

This report stems from a ticket (1429) so I am posting the report on behalf of the customer who noticed it. I did verify that the typo is present in Riak 1.1.2 release and Github master.

Thank you,

Brian

**Comment by seancribbs** [comment] 2012-05-22 13:08
Duplicate of basho/riak_kv#326

**Closed as completed by seancribbs** 2012-05-22 13:08 UTC
Labels: Kanban-Done

**Comment by brianshumate** [comment] 2012-05-22 14:42
Sorry about that. I did do a search for "riak_client:stream_list_keys" prior to submitting, but nothing came up.
