### ISSUE TITLE
Investigate why 2i/list keys during cluster change misses keys easily

### ISSUE THREAD

**Issue by engelsanchez** [basho/riak#305] opened 2013-04-02 21:32 UTC
A coverage query like a 2i range may return less than the number of actual results during ownership transfers.  We have in place a mechanism to forward requests to nodes that have transferred ownership already for a grace period, so this should not happen as frequently as it's been seen by some customers and during riak_test runs.

**Comment by ivenhov** [comment] 2013-04-02 23:15
Here's the thread where I reported the issue
http://comments.gmane.org/gmane.comp.db.riak.user/10468

Easily reproducible with 3k keys, 3 nodes and 512 vnodes. With default 64 vnodes I could not reproduce it.
The only workaround to reliably list keys via 2i was to wait until transfer completes
Daniel

**Comment by ivenhov** [comment] 2013-06-22 20:46
I just wanted to check if there's any progress on that considering 1.4 is round the corner.

**Comment by jaredmorrow** [comment] 2014-03-24 18:25
There was a lot of work done in 1.4.x regarding 2i, and I suspect this is fixed. 

I'm closing for now, unless @engelsanchez indeed thinks this is still an issue.

**Closed as completed by jaredmorrow** 2014-03-24 18:25 UTC
Labels: Bug, Kanban-Backlog
