### ISSUE TITLE
no such file or directory: 'c_src/system/lib/libsnappy.a'

### ISSUE THREAD

**Issue by gordonad** [basho/riak#166] opened 2012-06-14 23:36 UTC
I am trying to install on a Mac OSX Lion, all updates done,  Erlang R15B01 (erts-5.9.1), Xcode current.

I clone Riak, and when I attempt to build with "make rel" or "make all" both give me the same error: 

clang: error: no such file or directory: 'c_src/system/lib/libsnappy.a'
ERROR: cc c_src/eleveldb.o -L/lib -L/lib -L/lib -bundle -flat_namespace -undefined suppress  -L/usr/local/Cellar/erlang/R15B01/lib/erlang/lib/erl_interface-3.7.7/lib -lerl_interface -lei c_src/leveldb/libleveldb.a c_src/system/lib/libsnappy.a -lstdc++ -o priv/eleveldb.so failed with error: 1 and output:
clang: error: no such file or directory: 'c_src/system/lib/libsnappy.a'

**Comment by khill** [comment] 2012-06-19 18:29
In your cloned directory, you should have the following file:

riak/deps/eleveldb/c_src/system/lib/libsnappy.a

It sounds like it's not being built.  You could try running "./rebar compile" and see what errors you see.

**Comment by PharkMillups** [comment] 2012-06-19 18:43
@gordonad It looks like the problem is Clang. [Riak needs GCC](http://wiki.basho.com/Installing-Riak-from-Source.html). Any chance you can take another pass at the install with that?

**Comment by PharkMillups** [comment] 2012-06-26 22:09
@gordonad Any resolution on this?

**Comment by runesl** [comment] 2012-08-22 11:07
On my machine (OpenSuse 64bit) i got the same error: no such file or directory: 'c_src/system/lib/libsnappy.a

Because lib was actually called lib64, this fixed it for me:

cd deps/eleveldb/c_src/system
ln -s lib64 lib

After this I can build Riak 1.2.0.

**Comment by PharkMillups** [comment] 2012-08-22 13:58
I'm going to close this for now. If it rears its head again on 1.2, let us know.

**Closed as completed by PharkMillups** 2012-08-22 13:58 UTC
Labels: Kanban-Backlog

**Comment by marcelloceschia** [comment] 2012-11-14 10:24
same issue with riak 1.2.1, I need to symlink lib64 -> lib on openSuSE 64bit

**Comment by crodas** [comment] 2013-03-17 07:30
I had the same issue with OpenSuse 64 bits and I fixed with issue with 

```
ln -s $(pwd)/deps/eleveldb/c_src/system/lib64/ $(pwd)/deps/eleveldb/c_src/system/lib

```
