### ISSUE TITLE
frozen riak stop [JIRA: RIAK-1663]

### ISSUE THREAD

**Issue by cipy** [basho/riak#685] opened 2015-02-19 11:49 UTC
Hi,

`riak stop` freezes with the below error instead of stopping correctly

```
2015-02-19 10:59:38.299 [info] <0.96.0>@riak_core_sysmon_handler:handle_event:97 Monitor got {suppressed,port_events,1}
2015-02-19 10:59:38.730 [error] <0.11487.0> Supervisor {<0.11487.0>,poolboy_sup} had child riak_repl_fullsync_worker started with riak_repl_fullsync_worker:start_link([{name,{local,riak_repl2_rtsink_pool}},{worker_module,riak_repl_fullsync_worker},{worker_args,[]},...]) at undefined exit with reason shutdown in context shutdown_error
2015-02-19 10:59:38.731 [info] <0.1441.0>@riak_repl_app:stop:119 Stopped application riak_repl
2015-02-19 10:59:38.744 [info] <0.798.0>@riak_kv_app:prep_stop:209 Stopping application riak_kv - marked service down.
2015-02-19 10:59:38.745 [info] <0.798.0>@riak_kv_app:prep_stop:213 Unregistered pb services
2015-02-19 10:59:38.745 [info] <0.798.0>@riak_kv_app:prep_stop:218 unregistered webmachine routes
2015-02-19 10:59:38.745 [info] <0.798.0>@riak_kv_app:prep_stop:220 all active put FSMs completed
2015-02-19 10:59:38.775 [info] <0.876.0>@riak_kv_js_vm:terminate:240 Spidermonkey VM (pool: riak_kv_js_reduce) host stopping (<0.876.0>)
2015-02-19 10:59:38.775 [info] <0.883.0>@riak_kv_js_vm:terminate:240 Spidermonkey VM (pool: riak_kv_js_hook) host stopping (<0.883.0>)
```

**Comment by cmeiklejohn** [comment] 2015-02-19 14:54
This bug should be filed against `riak_ee`.

**Comment by ssylvester87** [comment] 2015-04-01 15:09
I have observed this behavior when all nodes in a multi-cluster realtime-replication configuration are issued a stop command simultaneously (via an automation tool such as Ansible). Failed repl leadership negotiation seems to cause a race condition when the operation times out and riak stop never finishes.

**Comment by Basho-JIRA** [comment] 2015-04-07 15:01
An ESL customer has been experiencing a similar issue. Attaching riak-debug. 

**_[posted via JIRA by Bryan Hunt]**_

**Comment by Basho-JIRA** [comment] 2015-04-07 19:43
Customer: William Hill via ESL. 
Version: 1.4.12 

***[posted via JIRA by Seema Jethani]***

**Comment by Basho-JIRA** [comment] 2015-04-15 13:17
I am not convinced William Hill are seeing this specific issue. I have asked for further troubleshooting by ESL. As such the prioritisation should not be based on William Hill needing this fixed. 

***[posted via JIRA by Dan Brown]***

**Comment by Basho-JIRA** [comment] 2015-04-28 23:07
https://github.com/basho/riak/issues/685 

**_[posted via JIRA by Deborah Rakow]**_

**Comment by Basho-JIRA** [comment] 2015-06-26 22:32
Jon M confirmed code merged to 2.0.6 on 6/25/15.  Dev is done. Now just waiting to go into additional releases.  

**_[posted via JIRA by Patricia Brewer]**_

**Closed as completed by Basho-JIRA** 2015-06-26 22:32 UTC
Labels: Bug, JIRA: Closed, JIRA: Done

**Comment by Basho-JIRA** [comment] 2015-06-29 14:45
Can the fix or commit be linked on this ticket? 

**_[posted via JIRA by Dan Brown]**_

**Comment by Basho-JIRA** [comment] 2015-07-09 20:15
This is linked to GH Riak/685.  [~dbrown] are you looking for something different?  

**_[posted via JIRA by Patricia Brewer]**_

**Comment by Basho-JIRA** [comment] 2015-07-09 20:21
This is linked to GH Riak/685.  [~dbrown] are you looking for something different?  This fix didn't go into 2.0.6.  Needs to go in a future release.   

**_[posted via JIRA by Patricia Brewer]**_

**Comment by Basho-JIRA** [comment] 2015-07-21 10:04
Thanks Patricia. I would like to know which version of Riak this will be available in and would like a link to the commit (not the GH issue) of the code change that fixes this. 

**_[posted via JIRA by Dan Brown]**_

**Comment by Basho-JIRA** [comment] 2016-03-04 17:33
It's been long enough that Jon M and others do not remember the specific context of any fix which may or may not have been merged into riak_kv/leveldb/eleveldb. There doesn't seem to be any commits in the time range of this ticket which would make sense as being a fix for this issue.

The attached riak_debug shows a riak node that is out of disk space failing to stop at all (much less gracefully.) It's difficult to say from the debug whether the "out of disk space" is the root cause of the failure or if there's some deeper defect for which the disk space problem is coincidental.

For now we should close this ticket and open a backlog item about the out of disk space issue (which requires investigation and a debug session) and if this reoccurs in the future, we ought to open a fresh ticket. 

**_[posted via JIRA by Mark Allen]**_

**Comment by n920094** [comment] 2017-07-10 03:06
I am facing this issue in Riak KV 2.1.3.
I'd like to try leadership reelection to confirm if it is a workaround of this issue.
Does anyone know how to reelect cluster_leader by riak attach ?
PS.
I previously did exit(riak_repl2_leader:helper_pid(), reelect) in 1.4.10.
