### ISSUE TITLE
riak-admin bucket-type status <name> always returns non-zero exit code

### ISSUE THREAD

**Issue by superstructor** [basho/riak#557] opened 2014-06-11 01:56 UTC
`riak-admin bucket-type status default` (or any other bucket type name) always returns a `1` as the exit code despite appearing to complete successfully. This makes scripting of `riak-admin` commands and detecting genuine errors troublesome. I am on Mac OS X 10.9.3 using the official Basho 2.0.0-beta1 package for OS X.

**Comment by jrwest** [comment] 2014-06-11 02:39
This is a duplicate of https://github.com/basho/riak_kv/issues/930. The changes in the associated pull request will be included in the next beta or release candidate release. thanks!

**Closed as completed by jrwest** 2014-06-11 02:39 UTC
