### ISSUE TITLE
Riak build issue on Mac OS 10.7 using lzo from MacPorts

### ISSUE THREAD

**Issue by kientzlecatch** [basho/riak#296] opened 2013-03-21 00:02 UTC
I just installed Erlang r15b01 using "kerl", then checked out Riak git master using:

$ git clone git://github.com/basho/riak.git

The build then failed because of a missing dependency on lzo/lzo1x.h:

$ cd riak
$ make rel
.... many build messages ...
libtool: link: ( cd ".libs" && rm -f "libsnappy.la" && ln -s "../libsnappy.la" "libsnappy.la" )
c++ -DHAVE_CONFIG_H -I.      -Wall -O3 -fPIC -MT snappy_unittest-snappy_unittest.o -MD -MP -MF .deps/snappy_unittest-snappy_unittest.Tpo -c -o snappy_unittest-snappy_unittest.o `test -f 'snappy_unittest.cc' || echo './'`snappy_unittest.cc
In file included from snappy_unittest.cc:39:
snappy-test.h:106:23: error: lzo/lzo1x.h: No such file or directory

This can be installed via MacPorts:

$ sudo port install lzo

But the build still fails as above.  Building using MacPorts lzo requires:

$ make clean && CPPFLAGS=-I/opt/local/include make rel

**Comment by jaredmorrow** [comment] 2013-04-12 13:29
I haven't been able to reproduce on any OSX machine I've tried.  I have installed the xcode command line tools on every machine as a base requirement.  For now I'm going to close this because it doesn't seem to be an issue in Riak.

**Closed as completed by jaredmorrow** 2013-04-12 13:29 UTC
Labels: Kanban-Backlog

**Comment by lusis** [comment] 2013-09-03 15:31
If anyone finds this with google, snappy doesn't use CPPFLAGS, it uses CXXFLAGS. Set that properly before make rel and things should build nicely
