### ISSUE TITLE
build errors

### ISSUE THREAD

**Issue by btv** [basho/riak#340] opened 2013-06-22 02:05 UTC
I'm on ArchLinux using erlang 16B01.

When trying to use the fast track documentation, trying to do the step "make all" I get this error:

```
./rebar compile
==> Entering directory `/home/bryce/Downloads/riak-1.3.2/deps/lager_syslog'
==> Entering directory `/home/bryce/Downloads/riak-1.3.2/deps/lager'
==> lager (compile)
ERROR: OTP release R16B01 does not match required regex R14B0[234]|R15
make: *** [compile] Error 1
```

Oddly enough I was able to "make" within both the deps/lager and lager_syslog directories. So I'm not sure where in the build process this error is occurring.

Happy to help test in anyway.

**Comment by jaredmorrow** [comment] 2013-06-22 03:07
We don't test against R16B01 yet that's why you got an error.  If you
really want to build against R16 instead of R15 just change the regex in
Riak's rebar.config.

**Comment by btv** [comment] 2013-06-26 04:23
Thank you Jared.

Can I assist at all by running tests? Is there a test suite to run?

**Comment by jaredmorrow** [comment] 2013-06-26 04:42
Developers at Basho already run R16B01 on a daily basis so I don't think there would be a problem functionality wise.  The reason we are slow to move Erlang VM's is due to our use of NIF's for our backends and the slight nuances we've found between even minor releases of Erlang.  The testing needed for 16B01 will probably be complex performance / scheduling testing to qualify it.  

I'd say if you are comfortable with the performance I don't see another reason why you couldn't run Riak on R16.  FWIW we did patch R15B01 with R16B01's scheduler changes, so that has an upgrade path going forward for us.

**Comment by jaredmorrow** [comment] 2013-06-26 04:43
I will go ahead and close this as not a bug, but please feel free to continue the conversation after it closes.

**Closed as completed by jaredmorrow** 2013-06-26 04:43 UTC
Labels: Kanban-Backlog

**Comment by btv** [comment] 2013-06-28 04:17
So I came across some compile errors with 1.3.2 and R16B01. Should I post them here or would you like new bug submitted (after checking if they are already submitted of course ;) )?

**Comment by evanmcc** [comment] 2013-06-28 04:19
The 1.3 and 1.4 lines are unlikely to ever support R16.

**Comment by jaredmorrow** [comment] 2013-06-28 05:06
The effort to remove incompatibilities happened in the 1.4 development cycle, so it is no surprise you found some issues in 1.3.2.  Post 1.4, our plan is to move to R16.

**Comment by btv** [comment] 2013-06-29 05:47
Thank you Jared for the information. Arch (and fedora 19) seemed both to have moved to R16. I'll have to find another way to play with Riak while I patiently wait for R16 compatibility.

I wouldn't mind helping out, but my Erlang & C skills are pretty weak, not sure where I could be of help.

**Comment by jaredmorrow** [comment] 2013-06-29 06:08
Building Erlang from source is quite easy

We have a simple guide for linux here: http://docs.basho.com/riak/latest/tutorials/installation/Installing-Erlang/#Installing-on-GNU-Linux

```
* Build Erlang R15B01 from source 
* add its `bin` directory to your path
* build Riak as you normally would.
```
